WebApplicationMVC/Models/Book.cs
namespace WebApplicationMVC.Models
{
    public class Book
    {
        public string Name { get; set; }
        public int Price { get; set; }
        public string Author { get; set; }
    }
}

WebApplicationMVC/Models/Employe.cs
namespace WebApplicationMVC.Models
{
    public class Employe
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }

        public int EmpSalary { get; set; }
    }
}

WebApplicationMVC/Models/Employee.cs
namespace WebApplicationMVC.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int Salary { get; set; }
    }
}

WebApplicationMVC/Models/ErrorViewModel.cs
namespace WebApplicationMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationMVC/Models/Product.cs
namespace WebApplicationMVC.Models;

public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }

    public int price { get; set; }
}

WebApplicationMVC/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationMVC.Models;

namespace WebApplicationMVC.Controllers
{
    public class BookController : Controller
    {
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Book book)
        {
            ViewBag.Name =book.Name;
            ViewBag.Price= book.Price;
            ViewBag.Author= book.Author;
            return View("Show");  
        }
    }
}

WebApplicationMVC/Controllers/EmployeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationMVC.Models;
using System.Diagnostics;

namespace WebApplicationMVC.Controllers
{
    public class EmployeController : Controller
    {
        public IActionResult EmpList()
        {
            List<Employe> employes = new List<Employe>()
            {
                new Employe{EmpId =101 , EmpName="Pranit", EmpSalary=2500},
                new Employe{EmpId =102 , EmpName="Arun",   EmpSalary=3500},
                new Employe{EmpId =103 , EmpName="Ajay",   EmpSalary=4500},
                new Employe{EmpId =104 , EmpName="Mahesh", EmpSalary=6500},

            };

            ViewData["EmpList"]= employes;
            ViewBag.EmpList = employes;
            return View();
        }
    }
}

WebApplicationMVC/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationMVC.Models;

namespace WebApplicationMVC.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult EmployeeList()
        {

            return View();
        }

        [HttpPost]
        public IActionResult EmployeeList(Employee Emp)
        {

            ViewBag.Id = Emp.Id;
            ViewBag.Name = Emp.Name;
            ViewBag.Salary = Emp.Salary;
            return View("EmployeeDetails");
        }
    }
}

WebApplicationMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplicationMVC.Models;

namespace WebApplicationMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["message"] = "Welcome to mvc core";
            List<string> colors = new List<string>() { "Red","Green","Blue","White","Black"};
            ViewData["ProductColor"]=colors;

            return View();
        }
        public IActionResult AboutUs()
        {
            return View();
        }
        public IActionResult ContactUs()
        {
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplicationMVC/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplicationMVC.Controllers
{
    public class PersonController : Controller
    {
        [HttpGet]
        public IActionResult PersonalDetails()
        {
            List<string> cities = new List<string>() { "select city ","Pune","Kolhapur","Nashik","Mumbai"};
            ViewData["cities"]=new SelectList(cities);  
            return View();
        }
        [HttpPost]
        public IActionResult PersonalDetails(IFormCollection form, ICollection<string> hobbies)
        {
            ViewBag.Name = form["pname"];
            ViewBag.Mobile = form["mobile"];
            ViewBag.Gender = form["Gender"];
            ViewBag.Hobbies = hobbies;
            ViewBag.City = form["cities"];
            return View("Details");
        }

    }

}

WebApplicationMVC/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplicationMVC.Models;

namespace WebApplicationMVC.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult ProductList()
        {
            List<Product> products = new List<Product>()
            {
                new Product{Id =101 , Name="Mouse", price=250},
                new Product{Id =102 , Name="Key-Board", price=350},
                new Product{Id =103 , Name="CPU", price=450},
                new Product{Id =104 , Name="Laptop", price=650},

            };
            ViewData["Prodlist"] = products;
            ViewBag.ProdList = products;
            return View();
        }
    }
}

WebApplicationMVC/Views/Book/Create.cshtml
@model WebApplicationMVC.Models.Book

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

WebApplicationMVC/Views/Book/Show.cshtml
@{
    ViewData["Title"] = "Show";
}

<h1>Show</h1>

<p>
    <b>Name</b> :@ViewBag.Name
</p>
<p>
    <b>Price</b> :@ViewBag.Price
</p>
<p>
    <b>Author</b> :@ViewBag.Author
</p>

WebApplicationMVC/Views/Employe/EmpList.cshtml
@{
    ViewData["Title"] = "EmpList";
}

<h1>Empolyee List</h1>
@if (ViewData["EmpList"] != null)
{
    <table class="table">
        <tr>
            <th>Employe Id</th>
            <th>Employe Name</th>
            <th>Employe Salary</th>
        </tr>
        @foreach (Employe p in (IEnumerable<Employe>)ViewData["EmpList"])
        {
                    <tr>
                        <td>@p.EmpId</td>
                        <td>@p.EmpName</td>
                        <td>@p.EmpSalary</td>
                    </tr>
        }
</table>
}
<h3>Employee List Using View Bag</h3>


        <table class ="table">
            <tr>
                <th>Employe Id</th>
                <th>Employe Name</th>
                <th>Employe Salary</th>
            </tr>
    @foreach (Employe p in ViewBag.EmpList)
    {
                        <tr>
                            <td>@p.EmpId</td>
                            <td>@p.EmpName</td>
                            <td>@p.EmpSalary</td>
                        </tr>
    }
        </table>

WebApplicationMVC/Views/Employee/EmployeeDetails.cshtml
@{
    ViewData["Title"] = "EmployeeDetails";
}

<h1>EmployeeDetails</h1>
<table class="table">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Salary</th>
    </tr>
    <tr>
        <th>@ViewBag.Id</th>
        <th>@ViewBag.Name</th>
        <th>@ViewBag.Salary</th>
    </tr>


</table>

WebApplicationMVC/Views/Employee/EmployeeList.cshtml
@model WebApplicationMVC.Models.Employee

@{
    ViewData["Title"] = "EmployeeList";
}

<h1>EmployeeList</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EmployeeList">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplicationMVC/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "AboutUs";
}

<h1>AboutUs</h1>

WebApplicationMVC/Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "ContactUs";
}

<h1>ContactUs</h1>

WebApplicationMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h3>
                @ViewData["message"]
            </h3>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12">
      
        </div>
    </div>
</div>


    

WebApplicationMVC/Views/Person/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Details";
}
<h1>Person Details</h1>

<table class="table">
    <tr>
        <th>Person Name</th>
        <td>@ViewBag.Name</td>
    </tr>
    <tr>
        <th>Person Mobile Number</th>
        <td>@ViewBag.Mobile</td>
    </tr>
    <tr>
        <th>Gender</th>
        <td>@ViewBag.Gender</td>
    </tr>
    <tr>
        <th>City</th>
        <td>@ViewBag.City</td>
    </tr>
    <tr>
        <th>Hobbies</th>
        <td>
            @foreach (String s in ViewBag.Hobbies)
            {
                <p>
                    @s
                </p>
            }
        </td>
    </tr>
</table>

WebApplicationMVC/Views/Person/PersonalDetails.cshtml
@{
    ViewData["Title"] = "PersonalDetails";
}

<h3>Personal Details</h3>
@using (Html.BeginForm())
{
    <div class="mb-3">
        <label>Enter Name</label>
        @Html.TextBox("pname")
    </div>
    <div class="mb-3">
        <label>Enter Mobile Number</label>
        @Html.TextBox("mobile")
    </div>
    <div class="mb-3">
        <label>Select Gender</label>
        @Html.RadioButton("Gender","Male") Male
        @Html.RadioButton("Gender","Female") Female
    </div>
    <div class="mb-3">
        <label>Select Hobbies</label>
        <input type="checkbox" name="hobbies" value="Sports" /> Sports
        <input type="checkbox" name="hobbies" value="Music" /> Music
        <input type="checkbox" name="hobbies" value="Reading" /> Reading
    </div>
    <div class="mb-3">
        <label>select city</label>
        @Html.DropDownList("cities")

    </div>
    <div class="mb-3">
        <input type="submit" value="Save Form" />
    </div>
}

WebApplicationMVC/Views/Product/ProductList.cshtml
@{
    ViewData["Title"] = "ProductList";
}

<h1>Product List</h1>
@if (ViewData["prodlist"] != null)
{
    <table class ="table">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Price</th>
        </tr>
        @foreach (Product p in (IEnumerable<Product>)ViewData["prodlist"])
        {
            <tr>
                <td>@p.Id</td>
                <td>@p.Name</td>
                <td>@p.price</td>
            </tr>
        }
    </table>
}
<h3>Product List Using View Bag</h3>


        <table class ="table">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Price</th>
            </tr>
        @foreach (Product p in ViewBag.ProdList)
        {
                    <tr>
                        <td>@p.Id</td>
                        <td>@p.Name</td>
                        <td>@p.price</td>
                    </tr>
        }
        </table>

WebApplicationMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">ContactUs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">AboutUs  </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ProductList">Product List  </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employe" asp-action="EmpList">Employee List  </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="PersonalDetails"> Details  </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Create"> Add Book </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmployeeList"> Employee Details </a>
                        </li>
                       
                       

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplicationMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>